name: Go build run and test workflow

on:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'

      # - name: Go build
      #   run: go build -v ./main.go

      # - name: Go test
      #   run: go test -v ./main.go
        
      - name: Go run
        run: go run ./main.go

      - uses: actions/upload-artifact@main
        with:
          name: Go artifacts
          path: public/

      - uses: actions/download-artifact@main
        with:
          name: Go artifacts
          path: public/download/

      - name: commit repository
        run: |
          git add .
          git commit -m "feat: up and down artifact"